### PR TITLE
Added main file designation to package.json.

### LINKED ISSUE #595: Make CommonJS friendly
Two changes are needed to make this project more friendly to Node. First, the NPM package should be renamed to "morris". I can't speak for all environments, but I cannot resolve "morris.js" using Webpack. Anyway, the NPM standard is to remove .js from the package name as it's assumed everything is js in the first place.

Also, please add 
"main": "morris.min"

to the package.json file. This allows me to use require.

### PR DESCRIPTION
**Pull request by tonymke**
Resolves #595 - can use morris with CommonJS.

### CODE REVIEW

**Comment by SebastianOsuna** [comment]
👍

**Comment by erikschlegel** [comment]
Can we please review /merge this PR as it's blocking our ability to use morris with webpack.

**Comment by SebastianOsuna** [comment]
@erikschlegel I was having the same problem, I published this PR to npm under morris.js.so if you want to use that while this gets merged.

**Comment by simonoff** [comment]
@SebastianOsuna welcome

**Comment by erikschlegel** [comment]
Thanks a bunch!!

**Pull request merged**
