### PR TITLE
Fix Line Chart Label colors when trend lines are not enabled.

### PR DESCRIPTION
**Pull request by arlaneenalra**
When using custom colors in a line chart and not using trend lines, labels have the wrong colors.  Currently, the colorFor function uses trendLineColors as a fall back even when trendLines are not enabled.  I've adjusted the code to use lineColors in this case and use trendLines otherwise.
screen shot 2015-01-07 at 2 43 33 pm

### CODE REVIEW

**Comment by JelteF** [comment]
Thanks for the pull request. I ran in to this bug myself as well, but haven't had the time to fix it yet. Could you change it so that it always falls back to LineColors, but just has an extra `else if` statement that checks for `type is 'trendline'`.

Also could you remove the compiled javascript from the commit?

**Comment by arlaneenalra** [comment]
How's that? It also pulls the duplication of the the lineColors lookup.

**Comment by JelteF** [comment]
Looks great. Could you squash the commits and remove the changes to the js files?

**Comment by arlaneenalra** [comment]
Should be done in PR #543

**Pull request closed without merging**
