### PR TITLE
Add an option to display the value of a bar in the bar itself

### PR DESCRIPTION
**Pull request by JelteF**
This only works for horizontal bars at the moment.

### CODE REVIEW

**Comment by csar2112** [comment]
How can add this functionality can you help me please 
Is necesary to add morris.bar.cofee???
can you explain me 

Thanks

**Comment by JelteF** [comment]
It is not yet in the compiled js, only in the coffee code. You can build a js file yourself though by cloning the repository and following these instructions: https://github.com/morrisjs/morris.js#developer-quick-start

**Comment by damiancardona** [comment]
I know this is out of date, but i just added the mods in my js and works! 

[morris.txt](https://github.com/morrisjs/morris.js/files/527823/morris.txt)
(translate was necessary)

edit: just change the ext. from txt to js

**Comment by nickluijtgaarden** [comment]
Thanks damian, the text file works fine.

And thanks JelteF for implementing this!

**Comment by Ramb20017** [comment]
nickluijtgaarden how its works? i ma new, and i cant make it

**Pull request merged**
