### PR TITLE
add option to fade in bars on hover

### PR DESCRIPTION
**Pull request by leriel**
I created this option for my own use and thought that maybe it will be beneficial to the library.

Unfortunately, animating fill-opacity works very wonky, so i changed that to animate whole bar opacity - that comes with updating test spec.

Not sure if this is beneficial to the library or not - looking forward to get your input

### CODE REVIEW

**Comment by JelteF** [comment]
Could you make a simple jsbin with this shown?

**Comment by leriel** [comment]
Sure, here it is: http://jsbin.com/vawacawufe/1/

Please don't mind the visible zero value, it is because i took rebuilt code from my master branch (includes changes from this branch and some others), as i don't have `hover-bars` branch built at hand

Also i should probably add this to /examples

**Comment by JelteF** [comment]
Looks cool. One question,  why have you changed fill-opacity to opacity?

**Comment by leriel** [comment]
My bad! I took another look and it turns out that changing fill-opacity to opacity was not necessary after all.

Branch (and this PR) has now updated code with 
* example file added
* spec unchanged
* reverted change to show zero-value (turns out i added that change to this branch by mistake)

Here is example on jsbin basing on rebuilt library
http://jsbin.com/tenanelete/1/edit?html,css,js,output

**Comment by leriel** [comment]
Is there anything else i can do ?

**Comment by JelteF** [comment]
Sorry, forgot about this a bit. Looks good to me.

**Comment by JelteF** [comment]
Thanks for the pull request.

**Comment by leriel** [comment]
No worries, glad i could help! :thumbsup:

**Pull request merged**
