### PR TITLE
Add horizontal barchart option

### LINKED ISSUE #110: add horizontal barchar
is possible horizontal barchar instead vertical like http://jsbin.com/uzosiq/2/embed?javascript,live

Thank you very much!

### PR DESCRIPTION
**Pull request by JelteF**
You can use a horizontal barchart by using the option `horizontal = true`. This fixes #110. Quite a lot of code had to be added to make this work. Please let me know if you think something should be handled differently. This also includes the fix I supplied in #447, since it was really small. So it fixes #382 as well.

### CODE REVIEW

**Comment by csar2112** [comment]
Hi
I need to put values inside each bar someone already do it?

**Comment by JelteF** [comment]
You can use the options added in this pull request: https://github.com/morrisjs/morris.js/pull/518

**Comment by vladkazantsev** [comment]
Hi, is there any way to get the horizontal functionality, can someone please tell me how to download a version or if ti is coming to the main one anytime soon?

**Comment by caiovms** [comment]
@JelteF First congratulations for the work. I'm a beginner in development and I'm using the sb-admin (asp net + bootstrap) template, which uses morris.js. I would like to use the horizontal bar chart. How can I make changes to my project?

**Pull request merged**
