### PR TITLE
RequireJS AMD support

### PR DESCRIPTION
**Pull request by heruan**
This commit enable Morris to be used as a RequireJS AMD module when AMD is detected. Otherwise, it will bind itself to `window.Morris` as usual.
E.g.

``` javascript
require( [ 'morris' ], function ( Morris ) {
    new MorrisLine({
        // options
    });
});
```

### CODE REVIEW

**Comment by Nadoedalo** [comment]
any luck of getting this pull request? RequireJS support is a must in 2015 for any-good JS lib.

**Comment by poifox** [comment]
:+1:

**Comment by booleanhunter** [comment]
is this P.R merged? I'm using Morris with Webpack and it's failing to build. What's the status?

**Comment by heruan** [comment]
Closing outdated PR.

**Pull request closed without merging**
